In [28]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

# Task1 - Clean the data

In [29]:
df['age'] = df['age'].fillna(df['age'].median())
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [30]:
df.duplicated().sum()

1

In [31]:
df[df.duplicated()]

   customer_id   age   city  gender  annual_income
4            2  35.0  Delhi  Female          80000

In [32]:
df.drop_duplicates(inplace=True)
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

# Task 2 - Encode Categorical columns

In [33]:
df = pd.get_dummies(df, columns=['city'], drop_first=True) # one hot encoding for city column
df

   customer_id   age  gender  annual_income  city_Mumbai
0            1  25.0    Male          40000         True
1            2  35.0  Female          80000        False
2            3  35.0  Female          60000        False
3            4  35.0    Male         120000         True
5            5  40.0    Male          95000        False

In [34]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})
print("The resulting DataFrame is:")
print(df)

The resulting DataFrame is:
   customer_id   age  gender  annual_income  city_Mumbai
0            1  25.0       1          40000         True
1            2  35.0       0          80000        False
2            3  35.0       0          60000        False
3            4  35.0       1         120000         True
5            5  40.0       1          95000        False

# Task 3- Scale Numerical Features

In [35]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

df_minmax = df.copy()
df_std = df.copy()
cols = ['age','annual_income']
minmax = MinMaxScaler()
df_minmax[cols] = minmax.fit_transform(df_minmax[cols])
print("DataFrame after Min-Max Scaling:")
print(df_minmax)

std = StandardScaler()
df_std[cols] = std.fit_transform(df_std[cols])
print("DataFrame after Standardization:")
print(df_std)

DataFrame after Min-Max Scaling:
   customer_id       age  gender  annual_income  city_Mumbai
0            1  0.000000       1         0.0000         True
1            2  0.666667       0         0.5000        False
2            3  0.666667       0         0.2500        False
3            4  0.666667       1         1.0000         True
5            5  1.000000       1         0.6875        False
DataFrame after Standardization:
   customer_id       age  gender  annual_income  city_Mumbai
0            1 -1.837117       1      -1.410970         True
1            2  0.204124       0       0.036179        False
2            3  0.204124       0      -0.687396        False
3            4  0.204124       1       1.483328         True
5            5  1.224745       1       0.578860        False

Min-Max Scaling rescales data into a fixed range (usually 0 to 1). It is preferred when you need bounded values (e.g., neural networks, distance-based models like KNN).
Standardization transforms data to have mean = 0 and standard deviation = 1. It is preferred when data follows a normal distribution or for models like Linear Regression and SVM.