# Importing Pandas

In [56]:
import pandas as pd

Created Dataframe using pd.DataFrame

In [58]:
data = {
    'EmployeeID': [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    'Name': ['Sarah', 'Michael', 'Jennifer', 'David', 'Lisa', 'James', 'Emma', 'Robert', 'Sophia', 'William'],
    'Department': ['Engineering', 'Sales', 'Marketing', 'Engineering', 'HR', 'Sales', 'Engineering', 'Marketing', 'Sales', 'HR'],
    'Salary': [85000, 62000, 71000, 92000, 58000, 68000, 78000, 75000, 65000, 60000],
    'Performance Score': [4, 3, 5, 5, 4, 4, 3, 4, 5, 3],
    'Years of Service': [5, 3, 7, 8, 4, 6, 2, 5, 4, 3]
}
df = pd.DataFrame(data)
df

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
1,202,Michael,Sales,62000,3,3
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
4,205,Lisa,HR,58000,4,4
5,206,James,Sales,68000,4,6
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5
8,209,Sophia,Sales,65000,5,4
9,210,William,HR,60000,3,3

Select and display only the 'Name', 'Department', and 'Salary' columns*

In [60]:
df[['Name','Department','Salary']]

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

Use iloc to display the employee at row position 5 (index 5)

In [62]:
df.iloc[5]

EmployeeID             206
Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 5, dtype: object

Use loc to display the employee with EmployeeID 208 (acess row by label)

In [64]:
df.set_index('EmployeeID').loc[208]

Name                    Robert
Department           Marketing
Salary                   75000
Performance Score            4
Years of Service             5
Name: 208, dtype: object

Filtered and display all employees from the 'Engineering' department by using accessing condition

In [66]:
df[df['Department'] == 'Engineering']

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

Using access condition, it will Filtered and display all employees with Salary greater than 70000

In [68]:
df[df['Salary'] >70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

Using Multi condition in accessing, i used '&' to Filter and display employees from 'Sales' department with Performance Score >= 4

In [70]:
df[(df['Department'] == 'Sales') & (df['Performance Score'] >= 4)]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

using sort_values method which sorts according to passed column, i Sort df by Salary in descending order and displayed the top 3 highest-paid employees

In [72]:
df_sorted = df.sort_values('Salary', ascending = False)

In [74]:
df_sorted.head(3)

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Engineering   92000                  5                 8
0         201  Sarah  Engineering   85000                  4                 5
6         207   Emma  Engineering   78000                  3                 2

using same method and passing multiple columns in a list, i Sort df by Department (ascending) and then by Salary (descending) within each department

In [76]:
df.sort_values(['Department', 'Salary'], ascending = [True,False])

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3